server {
	#ssl paramterer must be enabled on listening socket
	#digital handshake occurs between browser and server
	listen				443 ssl;
	listen				[::]:443 ssl;
	root				/var/www/html;

	server_name			josephinerandet.42.fr;
	#protocols for the secure socket layers. Establishes an encrypted link btw we browser and website server
	ssl_session_timeout 10m;
	ssl_protocols		TLSv1.2 TLSv1.3;
	#we generate those in the dockerfile, and now we tell the nginx container where to find the ssl asymetrical keys
	ssl_certificate     /etc/nginx/ssl/inception.crt;
	ssl_certificate_key /etc/nginx/ssl/inceptionkey.key;
	#location block specifies the / prefix 

	index index.php;

	location / {
		try_files $uri $uri/ /index.php?$args;
	}
	
	# this is how nginx connects to wordpress 
	location ~ [^/]\.php(/|$) {
		fastcgi_split_path_info			^(.+?\.php)(/.*)$;
		fastcgi_index					index.php;
		fastcgi_pass					wordpress:9000;

		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param QUERY_STRING    $query_string;
	}
}