events {

}

http {
	server {
		#ssl paramterer must be enabled on listening socket
		#digital handshake occurs between browser and server
		listen				443 ssl;
		#protocols for the secure socket layers. Establishes an encrypted link btw we browser and website server
		ssl_protocols		TLSv1.2 TLSv1.3;
		#we generate those in the dockerfile, and now we tell the nginx container where to find the ssl asymetrical keys
		ssl_certificate     /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inceptionkey.pem;
		#location block specifies the / prefix 
		root /var/www;
		index index.html;
		
		location / {
			try_files $uri $uri/ /index.hml =404;
		}
	}
}