services:
  nginx:
    build: requirements/nginx
    ports:
      - "443:80" #any traffic sent to 443 will be forwarded to 80 within the container
    #not sure at all about this 
  
  mariadb:
    build: requirements/mariadb
    entrypoint: ["docker-entrypoint-mariadb.sh", "mariadb"]
    command: ["-h", "localhost", "-p", "3306"]
    environment:
      - MARIADBPW: secret


volumes:

networks:
