# a service = a unit of work in docker compose. It will tell
#docker compose what images to build.
services:
  mariadb:
    build: requirements/mariadb
    volumes:
      - mariadb-database:/var/lib/mysql
    restart: always
    networks:
      - inception-network
    environment:
      - MARIADB_ROOT_PASSWORD=somewordpress
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=wordpress

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    volumes:
      - wp-content:/var/www/html
    restart: always
    networks:
      - inception-network
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
  
  nginx:
    depends_on:
      - wordpress
    hostname: nginx
    build: requirements/nginx
    ports:
      - "443:443" #any traffic sent to 443 will be forwarded to 80 within the container
    restart: always
    networks:
      - inception-network
    #not sure at all about this 


volumes:
  mariadb-database:
    driver: local
    driver_opts:
      o: bind
      device: /home/${HOSTUSERLOGIN}/data
  wp-content:
      driver: local
      driver_opts:
      o: bind
      device: /home/${HOSTUSERLOGIN}/data

#a network is a way for containers to communicate with eachother

networks:
  inception-network:
    driver: bridge

